# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: states.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='states.proto',
  package='mcts',
  syntax='proto2',
  serialized_pb=_b('\n\x0cstates.proto\x12\x04mcts\"S\n\x05State\x12\r\n\x05state\x18\x01 \x03(\x01\x12\x13\n\x0bprobability\x18\x02 \x03(\x01\x12\x0e\n\x06winner\x18\x03 \x01(\x01\x12\x16\n\x0e\x63urrent_player\x18\x04 \x01(\x05\"\'\n\x07Samples\x12\x1c\n\x07samples\x18\x01 \x03(\x0b\x32\x0b.mcts.State')
)




_STATE = _descriptor.Descriptor(
  name='State',
  full_name='mcts.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mcts.State.state', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='probability', full_name='mcts.State.probability', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winner', full_name='mcts.State.winner', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_player', full_name='mcts.State.current_player', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=105,
)


_SAMPLES = _descriptor.Descriptor(
  name='Samples',
  full_name='mcts.Samples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='mcts.Samples.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=146,
)

_SAMPLES.fields_by_name['samples'].message_type = _STATE
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Samples'] = _SAMPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'states_pb2'
  # @@protoc_insertion_point(class_scope:mcts.State)
  ))
_sym_db.RegisterMessage(State)

Samples = _reflection.GeneratedProtocolMessageType('Samples', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLES,
  __module__ = 'states_pb2'
  # @@protoc_insertion_point(class_scope:mcts.Samples)
  ))
_sym_db.RegisterMessage(Samples)


# @@protoc_insertion_point(module_scope)
